In [12]:
import torch

In [13]:
torch.__version__

'2.8.0+cu128'

In [14]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [15]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

In [16]:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [17]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


In [23]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(

            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2rd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits


In [24]:
model = NeuralNetwork(50, 3)

In [25]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [26]:
num_params = sum(
    p.numel() for p in model.parameters() if p.requires_grad
)
print("Total number of trainale model parameters:", num_params)

Total number of trainale model parameters: 2213


In [28]:
print(model.layers[0].weight)

Parameter containing:
tensor([[ 0.0781, -0.0389,  0.1315,  ..., -0.1409, -0.1026, -0.1358],
        [-0.0583,  0.1099,  0.1303,  ..., -0.0519, -0.0145,  0.1107],
        [ 0.0452, -0.0042, -0.0979,  ...,  0.0100,  0.0238,  0.0576],
        ...,
        [-0.0370, -0.1039,  0.1371,  ...,  0.0989,  0.0519,  0.1030],
        [ 0.0670,  0.0756,  0.0846,  ..., -0.1388,  0.0027, -0.0346],
        [ 0.0164,  0.1403,  0.0710,  ...,  0.1129, -0.1216,  0.0504]],
       requires_grad=True)


In [30]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [34]:
print(model.layers[0].bias)
print(model.layers[0].bias.shape)

Parameter containing:
tensor([-0.0732,  0.0494,  0.0212,  0.0169,  0.1145,  0.0183,  0.1380,  0.0054,
         0.0373, -0.0432,  0.1195, -0.0025, -0.1263, -0.0990,  0.1034,  0.0052,
        -0.0379,  0.0099,  0.0418,  0.0558,  0.1014, -0.0624, -0.0947, -0.0468,
         0.0701, -0.1290,  0.0504, -0.1295, -0.0085, -0.1155],
       requires_grad=True)
torch.Size([30])
